### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by liangzai-cool** [DoubleLabyrinth/how-does-navicat-encrypt-password#4]
```
MacBook-Pro:python3 xueliang$ python NavicatCryptoHelper.py -d "25C4********************************************************98D9"
Traceback (most recent call last):
  File "NavicatCryptoHelper.py", line 15, in <module>
    print(NavicatCipher.DecryptString(sys.argv[2]))
  File "/Users/xueliang/Downloads/how-does-navicat-encrypt-password-master/how-does-navicat-encrypt-password-master/python3/NavicatCrypto.py", line 80, in DecryptString
    return Result.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 0: invalid continuation byte
MacBook-Pro:python3 xueliang$ 
```
I run the command above, but an exception occurred(I have masked some character with `*`,  full string was from navicat connections.ncx file).

**Comment by DoubleLabyrinth** [comment]
You should add a argument `-ncx`:
```bash
python NavicatCryptoHelper.py -d -ncx "25C4B497961259055E538BEC3ECAB6AC439C5*****13558BA8E02B113AD498D9"
```

**Comment by DoubleLabyrinth** [comment]
By the way I shall give you a security warning:
The masked characters in your encrypted password string is too short. 
It is very easy to unmask those characters by brute-force attack.

As issue cannot be deleted, I strongly suggest you edit it and mask more characters.

**Comment by liangzai-cool** [comment]
Thank you very much for your warnging! 😄
I have update my issue, make more mask.

I tried the command:
`python3 xueliang$ python NavicatCryptoHelper.py -d -ncx "25C4********************************************************98D9"`
but got a new error:
```
MacBook-Pro:python3 xueliang$ python NavicatCryptoHelper.py -d -ncx "25C4********************************************************98D9"
Traceback (most recent call last):
  File "NavicatCryptoHelper.py", line 22, in <module>
    print(NavicatCipher.DecryptStringForNCX(sys.argv[3]))
  File "/Users/xueliang/Downloads/how-does-navicat-encrypt-password-master/how-does-navicat-encrypt-password-master/python3/NavicatCrypto.py", line 93, in DecryptStringForNCX
    AESCipher = AES.new(b'libcckeylibcckey', AES.MODE_CBC, iv=b'libcciv libcciv ')
  File "/Users/xueliang/.pyenv/versions/3.6.4/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/Users/xueliang/.pyenv/versions/3.6.4/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/Users/xueliang/.pyenv/versions/3.6.4/lib/python3.6/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
TypeError: 'iv' is an invalid keyword argument for this function
MacBook-Pro:python3 xueliang$
```
I have googled, `TypeError: 'iv' is an invalid keyword argument for this function`, but found no help result.

**Comment by DoubleLabyrinth** [comment]
I do not know what crypto package you have. Maybe you should switch to `pycryptodome` package

**Comment by liangzai-cool** [comment]
@DoubleLabyrinth yeah! I get my password!
Thanks a lot! And this tools is great!
